/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in many projects. It is checked in here so
// root-level TypeScript can understand the App Router types before first dev run.
